### PR TITLE
Navigating to a New Page

### PR DESCRIPTION
**Pull request by MapleSyyrup**
- navigate to a new page of each category

### CODE REVIEW

**Comment by Nei1eveN** [comment]
@MapleSyyrup please provide screenshots for each screens

**Comment by MapleSyyrup** [comment]
> @MapleSyyrup please provide screenshots for each screens

@Nei1eveN 
This is the Category Screen Widget.
image

After navigating to any category, this is how it looks like.
image

The user can tap on the back arrow to go back to the Category Screen.

**Comment by Nei1eveN** [comment]
> > @MapleSyyrup please provide screenshots for each screens
> 
> @Nei1eveN 
> This is the Category Screen Widget.
> image
> 
> After navigating to any category, this is how it looks like.
> image
> 
> The user can tap on the back arrow to go back to the Category Screen.

Looks good.

**Comment by Nei1eveN** [comment]
@MapleSyyrup please do merge changes from master to this branch

**Pull request merged**
